modLoader="javafml"
loaderVersion="[40,)"
license="None"
logoFile="banner.png"

[[mods]]
modId="owls"
version="1.3"
displayName="Feathery Messengers"
credits="§8Created by §5☆Lunar Eclipse Studios☆"
displayURL="https://lunareclipse.studio/creations/feathery-messengers"
issueTrackerURL="https://github.com/LunarEclipseStudios/feathery-messengers/issues"
authors="Bret06"
description='''Unleash the power of the skies with Feathery Messengers, the Minecraft mod that brings delivery owls to your world and allows you to send items soaring to your friends and allies with just a few clicks!'''

[[dependencies.owls]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20]"
    ordering="NONE"
    side="BOTH"

[[dependencies.owls]]
    modId="owls"
    mandatory=true
    versionRange="[1.3]"
    ordering="NONE"
    side="BOTH"



